      - name: Build and Generate CSS
        run: |
          npm install tailwindcss@latest postcss autoprefixer
          mkdir -p dist
          # Kreipiamės tiesiai į instaliuotą bin'ą, kad GitHub nebeturėtų klausimų
          ./node_modules/.bin/tailwindcss -i ./style.css -o ./dist/output.css --minify
